// <auto-generated />
using System;
using HinhLam_DataObject.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HinhLam_Dev.Migrations
{
    [DbContext(typeof(HinhLamDBContext))]
    [Migration("20230728055445_AddNews1")]
    partial class AddNews1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HinhLam_DataObject.Models.Category", b =>
                {
                    b.Property<string>("CateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CateNameCn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CateNameCN");

                    b.Property<string>("CateNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CateNameEN");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CateId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Consult", b =>
                {
                    b.Property<string>("ConsultId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contents")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCompany")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Response")
                        .HasColumnType("ntext");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ResponseStatus")
                        .HasColumnType("bit");

                    b.HasKey("ConsultId");

                    b.ToTable("Consult", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Content", b =>
                {
                    b.Property<string>("ContentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContentID");

                    b.Property<int>("ContentCount")
                        .HasColumnType("int");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("ContentsCn")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("ContentsCN");

                    b.Property<string>("ContentsEn")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("ContentsEN");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TitleCn")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TitleCN");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TitleEN");

                    b.HasKey("ContentId");

                    b.ToTable("Content", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Menu", b =>
                {
                    b.Property<string>("MenuId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HrefLink")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("HrefLinkCn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HrefLinkCN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("HrefLinkEn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HrefLinkEN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<int>("MenuCount")
                        .HasColumnType("int");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MenuNameCn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MenuNameCN");

                    b.Property<string>("MenuNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MenuNameEN");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("MenuId");

                    b.HasIndex("CateId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.MenuSubMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubMenuId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MenuId" }, "IX_MenuSubMenu_MenuId");

                    b.HasIndex(new[] { "SubMenuId" }, "IX_MenuSubMenu_SubMenuId");

                    b.ToTable("MenuSubMenu", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.News", b =>
                {
                    b.Property<string>("NewsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkHref")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TitleCn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TitleCN");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TitleEN");

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.NewsContent", b =>
                {
                    b.Property<string>("ContentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewsId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("ContentId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsContent", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.SubMenu", b =>
                {
                    b.Property<string>("SubMenuId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SubMenuID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("DescriptionCn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ntext")
                        .HasColumnName("DescriptionCN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ntext")
                        .HasColumnName("DescriptionEN")
                        .HasDefaultValueSql("(N'')");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubMenuCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleCn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TitleCN");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TitleEN");

                    b.HasKey("SubMenuId");

                    b.ToTable("SubMenu", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.SubMenuContent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubMenuId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContentId" }, "IX_SubMenuContent_ContentId");

                    b.HasIndex(new[] { "SubMenuId" }, "IX_SubMenuContent_SubMenuId");

                    b.ToTable("SubMenuContent", (string)null);
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Menu", b =>
                {
                    b.HasOne("HinhLam_DataObject.Models.Category", "Cate")
                        .WithMany("Menus")
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Menu_Category");

                    b.Navigation("Cate");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.MenuSubMenu", b =>
                {
                    b.HasOne("HinhLam_DataObject.Models.Menu", "Menu")
                        .WithMany("MenuSubMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HinhLam_DataObject.Models.SubMenu", "SubMenu")
                        .WithMany("MenuSubMenus")
                        .HasForeignKey("SubMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.NewsContent", b =>
                {
                    b.HasOne("HinhLam_DataObject.Models.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .HasConstraintName("FK_NewsContent_Content");

                    b.HasOne("HinhLam_DataObject.Models.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .HasConstraintName("FK_NewsContent_News");

                    b.Navigation("Content");

                    b.Navigation("News");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.SubMenuContent", b =>
                {
                    b.HasOne("HinhLam_DataObject.Models.Content", "Content")
                        .WithMany("SubMenuContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HinhLam_DataObject.Models.SubMenu", "SubMenu")
                        .WithMany("SubMenuContents")
                        .HasForeignKey("SubMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Category", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Content", b =>
                {
                    b.Navigation("SubMenuContents");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.Menu", b =>
                {
                    b.Navigation("MenuSubMenus");
                });

            modelBuilder.Entity("HinhLam_DataObject.Models.SubMenu", b =>
                {
                    b.Navigation("MenuSubMenus");

                    b.Navigation("SubMenuContents");
                });
#pragma warning restore 612, 618
        }
    }
}
